"""Zuordnung der Rechtsgrundlagen-PDFs zu Metadaten.

Grundlage: Rechtsgrundlagen/Uebersicht.txt. Die `rechtsgebiete`-Liste enthaelt
die Pruefbereich-Ids aus src/screening/pruefbereiche.js - ein Dokument kann zu
mehreren Rechtsgebieten gehoeren (z.B. BauGB -> Verkehr + Nutzungskonflikte).
"""

# Alle 9 Pruefbereich-Ids (muessen zu pruefbereiche.js passen).
RECHTSGEBIETE = [
    "naturschutz",
    "denkmalschutz",
    "wasserrecht",
    "leitungsrecht",
    "verkehrsrecht",
    "bodenschutz",
    "bauordnungsrecht",
    "waldrecht",
    "nutzungskonflikte",
]

# datei -> Metadaten
KORPUS = {
    "BNatSchG.pdf": {
        "gesetz": "Bundesnaturschutzgesetz",
        "kuerzel": "BNatSchG",
        "ebene": "bund",
        "stand": "2009 (jew. gueltige Fassung)",
        "quelle_url": "https://www.gesetze-im-internet.de/bnatschg_2009/",
        "rechtsgebiete": ["naturschutz"],
    },
    "2025-04-01-gesetz-zum-schutz-der-natur-in-nordrhei.pdf": {
        "gesetz": "Landesnaturschutzgesetz NRW",
        "kuerzel": "LNatSchG NRW",
        "ebene": "land",
        "stand": "2025-04-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01042025-gesetz-zum-schutz-der-natur-nordrhein-westfalen-landesnaturschutzgesetz/",
        "rechtsgebiete": ["naturschutz"],
    },
    "01-06-2022-nordrhein-westfaelisches-denkmalschutzg.pdf": {
        "gesetz": "Nordrhein-westfaelisches Denkmalschutzgesetz",
        "kuerzel": "DSchG NRW",
        "ebene": "land",
        "stand": "2022-06-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01062022-nordrhein-westfaelisches-denkmalschutzgesetz-denkmalschutzgesetz-dschg-nrw/",
        "rechtsgebiete": ["denkmalschutz"],
    },
    "01-01-2022-kulturgesetzbuch-fuer-das-land-nordrhei.pdf": {
        "gesetz": "Kulturgesetzbuch fuer das Land Nordrhein-Westfalen",
        "kuerzel": "KulturGB NRW",
        "ebene": "land",
        "stand": "2022-01-01",
        "quelle_url": "https://recht.nrw.de/lrgv/",
        "rechtsgebiete": ["denkmalschutz"],
        "kontext": True,
    },
    "WHG.pdf": {
        "gesetz": "Wasserhaushaltsgesetz",
        "kuerzel": "WHG",
        "ebene": "bund",
        "stand": "2009 (jew. gueltige Fassung)",
        "quelle_url": "https://www.gesetze-im-internet.de/whg_2009/",
        "rechtsgebiete": ["wasserrecht"],
    },
    "2021-12-29-bekanntmachung-der-neufassung-des-wasse.pdf": {
        "gesetz": "Landeswassergesetz NRW",
        "kuerzel": "LWG NRW",
        "ebene": "land",
        "stand": "2021-12-29",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/29122021-bekanntmachung-der-neufassung-des-wassergesetzes-fuer-das-land-nordrhein/",
        "rechtsgebiete": ["wasserrecht"],
    },
    "OGewV.pdf": {
        "gesetz": "Oberflaechengewaesserverordnung",
        "kuerzel": "OGewV",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/ogewv_2016/",
        "rechtsgebiete": ["wasserrecht"],
        "kontext": True,
    },
    "EnWG.pdf": {
        "gesetz": "Energiewirtschaftsgesetz",
        "kuerzel": "EnWG",
        "ebene": "bund",
        "stand": "2005 (jew. gueltige Fassung)",
        "quelle_url": "https://www.gesetze-im-internet.de/enwg_2005/",
        "rechtsgebiete": ["leitungsrecht"],
    },
    "TKG.pdf": {
        "gesetz": "Telekommunikationsgesetz",
        "kuerzel": "TKG",
        "ebene": "bund",
        "stand": "2021 (jew. gueltige Fassung)",
        "quelle_url": "https://www.gesetze-im-internet.de/tkg_2021/",
        "rechtsgebiete": ["leitungsrecht"],
    },
    "FStrG.pdf": {
        "gesetz": "Bundesfernstrassengesetz",
        "kuerzel": "FStrG",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/fstrg/",
        "rechtsgebiete": ["verkehrsrecht"],
    },
    "01-01-2025-strassen-und-wegegesetz-des-landes-nord.pdf": {
        "gesetz": "Strassen- und Wegegesetz NRW",
        "kuerzel": "StrWG NRW",
        "ebene": "land",
        "stand": "2025-01-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01012025-strassen-und-wegegesetz-des-landes-nordrhein-westfalen-strwg-nrw/",
        "rechtsgebiete": ["verkehrsrecht"],
    },
    "BauGB.pdf": {
        "gesetz": "Baugesetzbuch",
        "kuerzel": "BauGB",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/bbaug/",
        "rechtsgebiete": ["verkehrsrecht", "nutzungskonflikte", "naturschutz"],
    },
    "BBodSchG.pdf": {
        "gesetz": "Bundes-Bodenschutzgesetz",
        "kuerzel": "BBodSchG",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/bbodschg/",
        "rechtsgebiete": ["bodenschutz"],
    },
    "BBodSchV.pdf": {
        "gesetz": "Bundes-Bodenschutz- und Altlastenverordnung",
        "kuerzel": "BBodSchV",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/bbodschv/",
        "rechtsgebiete": ["bodenschutz"],
    },
    "2025-04-01-landesbodenschutzgesetz-fuer-das-land-n.pdf": {
        "gesetz": "Landesbodenschutzgesetz NRW",
        "kuerzel": "LBodSchG NRW",
        "ebene": "land",
        "stand": "2025-04-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01042025-landesbodenschutzgesetz-fuer-das-land-nordrhein-westfalen/",
        "rechtsgebiete": ["bodenschutz"],
    },
    "BImSchG.pdf": {
        "gesetz": "Bundes-Immissionsschutzgesetz",
        "kuerzel": "BImSchG",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/bimschg/",
        "rechtsgebiete": ["bodenschutz"],
        "kontext": True,
    },
    "01-01-2024-bauordnung-fuer-das-land-nordrhein-west.pdf": {
        "gesetz": "Landesbauordnung NRW 2018",
        "kuerzel": "BauO NRW 2018",
        "ebene": "land",
        "stand": "2024-01-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01012024-bauordnung-fuer-das-land-nordrhein-westfalen-landesbauordnung-2018-bauo-nrw/",
        "rechtsgebiete": ["bauordnungsrecht"],
    },
    "2021-12-29-nachbarrechtsgesetz-nachbg-nrw.pdf": {
        "gesetz": "Nachbarrechtsgesetz NRW",
        "kuerzel": "NachbG NRW",
        "ebene": "land",
        "stand": "2021-12-29",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/29122021-nachbarrechtsgesetz-nachbg-nrw/",
        "rechtsgebiete": ["bauordnungsrecht", "nutzungskonflikte"],
    },
    "BWaldG.pdf": {
        "gesetz": "Bundeswaldgesetz",
        "kuerzel": "BWaldG",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/bwaldg/",
        "rechtsgebiete": ["waldrecht"],
    },
    "2025-04-01-landesforstgesetz-fuer-das-land-nordrhe.pdf": {
        "gesetz": "Landesforstgesetz NRW",
        "kuerzel": "LFoG NRW",
        "ebene": "land",
        "stand": "2025-04-01",
        "quelle_url": "https://recht.nrw.de/lrgv/gesetz/01042025-landesforstgesetz-fuer-das-land-nordrhein-westfalen-landesforstgesetz-lfog/",
        "rechtsgebiete": ["waldrecht"],
    },
    "BauNVO.pdf": {
        "gesetz": "Baunutzungsverordnung",
        "kuerzel": "BauNVO",
        "ebene": "bund",
        "stand": "jew. gueltige Fassung",
        "quelle_url": "https://www.gesetze-im-internet.de/baunvo/",
        "rechtsgebiete": ["nutzungskonflikte"],
    },
}
